package com.ltbrew.brewbeer.persistence.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBBREW_STEP".
 */
public class DBBrewStep {

    private Long id;
    /** Not-null value. */
    private String stepId;
    private String act;
    private Integer f;
    private Integer pid;
    private String i;
    private Integer k;
    private Integer t;
    private Integer drn;
    private Integer slot;
    private long recipeId;

    public DBBrewStep() {
    }

    public DBBrewStep(Long id) {
        this.id = id;
    }

    public DBBrewStep(Long id, String stepId, String act, Integer f, Integer pid, String i, Integer k, Integer t, Integer drn, Integer slot, long recipeId) {
        this.id = id;
        this.stepId = stepId;
        this.act = act;
        this.f = f;
        this.pid = pid;
        this.i = i;
        this.k = k;
        this.t = t;
        this.drn = drn;
        this.slot = slot;
        this.recipeId = recipeId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getStepId() {
        return stepId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStepId(String stepId) {
        this.stepId = stepId;
    }

    public String getAct() {
        return act;
    }

    public void setAct(String act) {
        this.act = act;
    }

    public Integer getF() {
        return f;
    }

    public void setF(Integer f) {
        this.f = f;
    }

    public Integer getPid() {
        return pid;
    }

    public void setPid(Integer pid) {
        this.pid = pid;
    }

    public String getI() {
        return i;
    }

    public void setI(String i) {
        this.i = i;
    }

    public Integer getK() {
        return k;
    }

    public void setK(Integer k) {
        this.k = k;
    }

    public Integer getT() {
        return t;
    }

    public void setT(Integer t) {
        this.t = t;
    }

    public Integer getDrn() {
        return drn;
    }

    public void setDrn(Integer drn) {
        this.drn = drn;
    }

    public Integer getSlot() {
        return slot;
    }

    public void setSlot(Integer slot) {
        this.slot = slot;
    }

    public long getRecipeId() {
        return recipeId;
    }

    public void setRecipeId(long recipeId) {
        this.recipeId = recipeId;
    }

}
