package com.ltbrew.brewbeer.persistence.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.ltbrew.brewbeer.persistence.greendao.DBRecipe;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DBRECIPE".
*/
public class DBRecipeDao extends AbstractDao<DBRecipe, Long> {

    public static final String TABLENAME = "DBRECIPE";

    /**
     * Properties of entity DBRecipe.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RecipeId = new Property(1, String.class, "recipeId", false, "RECIPE_ID");
        public final static Property Id_type = new Property(2, String.class, "id_type", false, "ID_TYPE");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property Ref = new Property(4, String.class, "ref", false, "REF");
        public final static Property Cus = new Property(5, String.class, "cus", false, "CUS");
        public final static Property Wr = new Property(6, String.class, "wr", false, "WR");
        public final static Property Wq = new Property(7, String.class, "wq", false, "WQ");
    };

    private DaoSession daoSession;


    public DBRecipeDao(DaoConfig config) {
        super(config);
    }
    
    public DBRecipeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DBRECIPE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"RECIPE_ID\" TEXT NOT NULL UNIQUE ," + // 1: recipeId
                "\"ID_TYPE\" TEXT NOT NULL ," + // 2: id_type
                "\"NAME\" TEXT," + // 3: name
                "\"REF\" TEXT," + // 4: ref
                "\"CUS\" TEXT," + // 5: cus
                "\"WR\" TEXT," + // 6: wr
                "\"WQ\" TEXT);"); // 7: wq
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DBRECIPE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DBRecipe entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getRecipeId());
        stmt.bindString(3, entity.getId_type());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
 
        String ref = entity.getRef();
        if (ref != null) {
            stmt.bindString(5, ref);
        }
 
        String cus = entity.getCus();
        if (cus != null) {
            stmt.bindString(6, cus);
        }
 
        String wr = entity.getWr();
        if (wr != null) {
            stmt.bindString(7, wr);
        }
 
        String wq = entity.getWq();
        if (wq != null) {
            stmt.bindString(8, wq);
        }
    }

    @Override
    protected void attachEntity(DBRecipe entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DBRecipe readEntity(Cursor cursor, int offset) {
        DBRecipe entity = new DBRecipe( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // recipeId
            cursor.getString(offset + 2), // id_type
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // ref
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // cus
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // wr
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // wq
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DBRecipe entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRecipeId(cursor.getString(offset + 1));
        entity.setId_type(cursor.getString(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRef(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCus(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setWr(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setWq(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DBRecipe entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DBRecipe entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
