package com.ltbrew.brewbeer.persistence.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBSLOT".
 */
public class DBSlot {

    private Long id;
    private String slotStepId;
    private Integer slotId;
    /** Not-null value. */
    private String name;
    private long recipeId;

    public DBSlot() {
    }

    public DBSlot(Long id) {
        this.id = id;
    }

    public DBSlot(Long id, String slotStepId, Integer slotId, String name, long recipeId) {
        this.id = id;
        this.slotStepId = slotStepId;
        this.slotId = slotId;
        this.name = name;
        this.recipeId = recipeId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSlotStepId() {
        return slotStepId;
    }

    public void setSlotStepId(String slotStepId) {
        this.slotStepId = slotStepId;
    }

    public Integer getSlotId() {
        return slotId;
    }

    public void setSlotId(Integer slotId) {
        this.slotId = slotId;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public long getRecipeId() {
        return recipeId;
    }

    public void setRecipeId(long recipeId) {
        this.recipeId = recipeId;
    }

}
